#!/bin/bash
# =====================================================================
#  Regenerates the lock files scripts/run.sh installs the Python libraries from:
#    core/requirements.lock           everything in core/requirements.txt
#    core/requirements-devtools.lock  the part the setup guide needs first (pymobiledevice3)
#    core/requirements-build.lock     setuptools, to build hexdump (PyPI has no wheel for it)
#  Every dependency is at an exact version with the SHA-256 of each of its files, resolved
#  for the Python IVory ships (3.12) on macOS 14+, Apple Silicon and Intel, wheels only.
#  run.sh installs them with --require-hashes, so nothing unlisted or swapped gets in.
#  Where the two architectures can't share a version (cryptography has no Intel wheels
#  any more), the lock carries both, each behind a platform_machine marker.
#  Versions already in a lock are kept unless requirements.txt asks for others.
#
#    bash scripts/lock_python.sh            # after editing core/requirements.txt
#    bash scripts/lock_python.sh --upgrade  # also move the dependencies to their newest versions
# =====================================================================
set -euo pipefail

UV_VERSION=0.12.23
SETUPTOOLS_VERSION=84.0.0
PY_VERSION=3.12
export MACOSX_DEPLOYMENT_TARGET=14.0     # the oldest macOS IVory runs on (LSMinimumSystemVersion)
SDIST_ONLY=hexdump                       # built from source with the locked setuptools

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CORE="$ROOT/core"
TOOLS="$ROOT/build/lock-tools"
if [ ! -x "$TOOLS/bin/uv" ]; then
  echo "▶ Instaluji uv $UV_VERSION (jen poprvé)..."
  python3 -m venv "$TOOLS"
  "$TOOLS/bin/python" -m pip install -q --disable-pip-version-check "uv==$UV_VERSION"
fi
UV="$TOOLS/bin/uv"
UPGRADE=()
[ "${1:-}" = "--upgrade" ] && UPGRADE=(--upgrade)
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# resolve ARCH INPUT OUTPUT [uv args]: one architecture, with hashes. The lock already in OUTPUT's
# place is copied there first, because uv keeps the versions it finds in its output file.
resolve() {
  local arch="$1" in="$2" out="$3" previous="$4"; shift 4
  [ -f "$previous" ] && cp "$previous" "$out"
  "$UV" pip compile "$in" "$@" ${UPGRADE[@]+"${UPGRADE[@]}"} --python-version "$PY_VERSION" \
    --python-platform "$arch-apple-darwin" --only-binary :all: --no-binary "$SDIST_ONLY" \
    --generate-hashes --no-header --no-annotate --quiet -o "$out"
}

# merge ARM64 X86_64 LOCK: one file for both; a package whose version differs (or that only one
# of them needs) gets a platform_machine marker.
merge() {
  "$TOOLS/bin/python" - "$@" <<'PY'
import re, sys

def blocks(path):
    out, name = {}, None
    for line in open(path):
        if line.startswith("#") or not line.strip():
            continue
        if not line[0].isspace():
            name = re.split(r"[=; \\]", line, maxsplit=1)[0].lower().replace("_", "-").replace(".", "-")
            out[name] = []
        out[name].append(line.rstrip("\n"))
    return out

def marked(block, machine):
    head = block[0].removesuffix(" \\").split(" ;")[0]
    return [f'{head} ; platform_machine == "{machine}" \\'] + block[1:]

arm, intel = blocks(sys.argv[1]), blocks(sys.argv[2])
lines = [
    "# Generated by scripts/lock_python.sh from core/requirements.txt – don't edit by hand.",
    f"# Python 3.12, macOS 14+, Apple Silicon and Intel. scripts/run.sh installs it with --require-hashes.",
]
for name in sorted(arm.keys() | intel.keys()):
    a, i = arm.get(name), intel.get(name)
    if a == i:
        lines += a
    else:
        if a: lines += marked(a, "arm64")
        if i: lines += marked(i, "x86_64")
open(sys.argv[3], "w").write("\n".join(lines) + "\n")
PY
}

# lock INPUT LOCK [uv args]: both architectures into one lock. The unmerged results stay in
# $WORK/<lock name>.<arch> for the locks constrained by them.
lock() {
  local in="$1" lock="$2"; shift 2
  local base; base="$(basename "$lock")"
  for arch in aarch64 x86_64; do
    local constraint=()
    [ $# -gt 0 ] && constraint=(-c "$WORK/$1.$arch")
    resolve "$arch" "$in" "$WORK/$base.$arch" "$WORK/previous-$base" ${constraint[@]+"${constraint[@]}"}
  done
  merge "$WORK/$base.aarch64" "$WORK/$base.x86_64" "$lock"
}

# uv reads its preferences from a file without markers: strip them from the current locks
for f in requirements.lock requirements-devtools.lock; do
  [ -f "$CORE/$f" ] && sed -E 's/ ; platform_machine == "[a-z0-9_]+"//' "$CORE/$f" > "$WORK/previous-$f"
done

echo "▶ Zamykám core/requirements.lock"
lock "$CORE/requirements.txt" "$CORE/requirements.lock"
echo "▶ Zamykám core/requirements-devtools.lock"
grep -i '^pymobiledevice3==' "$CORE/requirements.txt" > "$WORK/devtools.in"
lock "$WORK/devtools.in" "$CORE/requirements-devtools.lock" requirements.lock
echo "▶ Zamykám core/requirements-build.lock"
echo "setuptools==$SETUPTOOLS_VERSION" > "$WORK/build.in"
lock "$WORK/build.in" "$CORE/requirements-build.lock"
echo "✔ Hotovo: $(grep -c '^[a-zA-Z]' "$CORE/requirements.lock") řádků v requirements.lock," \
  "$(grep -c 'platform_machine' "$CORE/requirements.lock") podle architektury"
